import { z } from "zod";

const availableModules = [
  "dashboard",
  "leads",
  "customers",
  "quotations",
  "invoices",
  "payments",
  "tasks",
  "reports",
  "support",
  "deployments",
  "assets",
  "field_jobs",
  "inventory",
  "suppliers",
  "restocking",
  "expenses",
  "audit",
  "users",
  "settings",
  "messages",
] as const;

export const createUserSchema = z.object({
  first_name: z.string().min(1, "First name is required"),
  last_name: z.string().optional(),
  email: z.string().email("Enter a valid email"),
  password: z.string().min(6, "Password must be at least 6 characters"),
  username: z.string().min(3, "Username is required"),
  role: z.enum(["admin", "staff"]),
  job_title: z.string().optional(),
  phone: z.string().optional(),
  address: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  hire_date: z.string().optional(),
  birthday: z.string().optional(),
  employee_number: z.string().optional(),
  force_password_change: z.boolean().default(false),
  allowed_modules: z.array(z.enum(availableModules)).default([]),
});

export const updateUserSchema = z.object({
  first_name: z.string().min(1, "First name is required"),
  last_name: z.string().optional(),
  email: z.string().email("Enter a valid email"),
  username: z.string().min(3, "Username is required"),
  role: z.enum(["admin", "staff"]),
  job_title: z.string().optional(),
  phone: z.string().optional(),
  address: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  hire_date: z.string().optional(),
  birthday: z.string().optional(),
  employee_number: z.string().optional(),
  force_password_change: z.boolean().default(false),
  allowed_modules: z.array(z.enum(availableModules)).default([]),
  is_active: z.enum(["true", "false"]),
});