export const MODULE_PRESETS = {
  sales: [
    "dashboard",
    "leads",
    "customers",
    "quotations",
    "invoices",
    "payments",
    "tasks",
    "reports",
    "notifications",
    "search",
  ],

  support: [
    "dashboard",
    "customers",
    "support",
    "tasks",
    "assets",
    "field_jobs",
    "engineer_daily",
    "reports",
    "notifications",
    "search",
  ],

  engineering: [
    "dashboard",
    "projects",
    "field_jobs",
    "engineer_daily",
    "deployments",
    "assets",
    "inventory",
    "support",
    "tasks",
    "reports",
    "notifications",
    "search",
  ],

  operations: [
    "dashboard",
    "projects",
    "customers",
    "tasks",
    "deployments",
    "assets",
    "field_jobs",
    "reports",
    "notifications",
    "search",
  ],

  inventory: [
    "dashboard",
    "inventory",
    "suppliers",
    "restocking",
    "field_jobs",
    "reports",
    "notifications",
    "search",
  ],

  finance: [
    "dashboard",
    "customers",
    "invoices",
    "payments",
    "expenses",
    "suppliers",
    "supplier_payables",
    "restocking",
    "reports",
    "notifications",
    "search",
  ],

  hr: [
    "dashboard",
    "users",
    "reports",
    "audit_logs",
    "settings",
    "search",
  ],

  admin: [
    "dashboard",
    "leads",
    "customers",
    "quotations",
    "invoices",
    "payments",
    "tasks",
    "projects",
    "reports",
    "support",
    "notifications",
    "deployments",
    "assets",
    "field_jobs",
    "engineer_daily",
    "inventory",
    "suppliers",
    "supplier_payables",
    "restocking",
    "expenses",
    "audit_logs",
    "users",
    "settings",
    "search",
    "messages",
  ],
} as const;
